### ISSUE TITLE
Todo's

### ISSUE THREAD

**Issue by ivanseidel** [ivanseidel/Is-Now-Illegal#1]
## IMPORTANT TODO's
- [x] Add title/content description to Page meta-data
- [x] Add "Illegalize something else" when in the GIF page viewer (goes back to original url)
- [x] Sanitize URL (Convert `-` to spaces, and `--` double dashes as spaces). like: `/something-else` becomes: `something else`
- [ ] Animated Loading
- [x] Avoid showing cursos on loading button (just normal arrow)
- [x] Improve colors/opacities
-----
### Later TODO's
- [ ] Top Illegalized
- [ ] Realtime Last 5 illegalized things

**Comment by brunolemos** [comment]
- [x] Fix words with space
- [x] Make Download button work for real
- [ ] Better sharing on social medias (specially twitter) (#3)

**Comment by sarim** [comment]
For making the download button work for real, why not use the html5 download attribute on `a` element? I can send a PR.

**Comment by brunolemos** [comment]
@sarim Please do!

**Comment by brunolemos** [comment]
@sarim: Fixed on https://github.com/ivanseidel/Is-Now-Illegal/commit/aee4e7a24d623763dbf084f6a7303f240cc3c9e9, thanks!

**Comment by StephenKoller** [comment]
Can you add emoji support?
Would love to see Trump trying to make 💩💩💩 illegal.

**Comment by gs-akhan** [comment]
Also real time counter for total things illegalized 
:)
Thanks

**Comment by WansonSwanson** [comment]
Do you have any plans of making an API for this?
